# Generated by Django 5.2 on 2025-04-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('doc_type', models.CharField(max_length=50)),
                ('doc_image', models.ImageField(upload_to='documents/')),
                ('audience', models.TextField(blank=True, null=True)),
                ('known_as', models.BooleanField(default=False)),
                ('personal_details', models.JSONField()),
                ('doc_number', models.CharField(max_length=100)),
                ('links', models.JSONField()),
                ('address', models.JSONField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Verified'), (2, 'Pending')], default=2)),
            ],
        ),
    ]
